/*
You are given two strings s and t.

String t is generated by random shuffling string s and 
then add one more letter at a random position.

Return the letter that was added to t.

Example:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
*/

s = "abcd";
t = "abcde";

var findTheDifference = function (s, t) {
  let sSorted = [];
  let tSorted = [];
  for (let i = 0; i < s.length; i++) {
    sSorted.push(s[i]);
  }
  for (let i = 0; i < t.length; i++) {
    tSorted.push(t[i]);
  }
  sSorted.sort();
  tSorted.sort();

  for (let i = 0; i < tSorted.length; i++) {
    if (sSorted[i] === tSorted[i]) {
      continue;
    } else return tSorted[i];
  }
};

console.log(findTheDifference(s, t));
